### ISSUE TITLE
Is there any ability to use calendar-scheduler with resources?

### ISSUE THREAD

**Issue by AlesikAndrey** [ng-fullcalendar/ng-fullcalendar#113]
It would be nice to group events by resources.

**Comment by Jamaks** [comment]
still an issue?

**Comment by ajaykumar22** [comment]
still an issue?

**Comment by AlesikAndrey** [comment]
Yep

**Comment by ajaykumar22** [comment]
any solution to resolve the above issue?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
