### ISSUE TITLE
Missing property in Agenda Options

### ISSUE THREAD

**Issue by danielok1993** [ng-fullcalendar/ng-fullcalendar#115]
In the release, 3.6.0 Fullcalendar added a new property called [agendaEventMinHeight ](https://fullcalendar.io/docs/agendaEventMinHeight), which allows setting a minimum height for the agenda items that have a low start and end time. I have added it manually to index.d.ts and it is working fine.

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
