### ISSUE TITLE
How to get td attribute properties using jQuery MouseOver 

### ISSUE THREAD

**Issue by Gopikrishn** [ng-fullcalendar/ng-fullcalendar#116]
Hi there,

In my Full calendar application when we right click on particular event I just need Minute Time,

So I changed renderSlatRowHtml function of fullcalendar.js file  

           renderSlatRowHtml: function() {
            var view = this.view;
            var calendar = view.calendar;
            var theme = calendar.theme;
            var isRTL = this.isRTL;
            var dateProfile = this.dateProfile;
            var html = '';
            var slotTime = moment.duration(+dateProfile.minTime); // wish there was .clone() for durations
            var slotIterator = moment.duration(0);
            var slotDate; // will be on the view's first day, but we only care about its time
            var isLabeled;
            var axisHtml;

            // Calculate the time for each slot
            while (slotTime < dateProfile.maxTime) {
                slotDate = calendar.msToUtcMoment(dateProfile.renderUnzonedRange.startMs).time(slotTime);
                isLabeled = isInt(divideDurationByDuration(slotIterator, this.labelInterval));

                axisHtml =
                    '<td class="fc-axis fc-time ' + theme.getClass('widgetContent') + '" ' + view.axisStyleAttr() + '>' +
                    (isLabeled ?
                        '<span>' + // for matchCellWidths
                        htmlEscape(slotDate.format(this.labelFormat)) +
                        '</span>' :
                        ''
                    ) +
                    '</td>';

                html +=
                    '<tr  name ="' + slotDate.format('HH:mm:ss') + '" data-time="' + slotDate.format('HH:mm:ss') + '"' +
                    (isLabeled ? '' : ' class="fc-minor KRISHN"') +
                    '>' +
                    (!isRTL ? axisHtml : '') +
                    '<td name= RAVI (click)="create()" class=" KRISHN ' + theme.getClass('widgetContent') + '"/>' +
                    (isRTL ? axisHtml : '') +
                    "</tr>";

                slotTime.add(this.slotDuration);
                slotIterator.add(this.slotDuration);
            }
            return html;
        }

I added jQuery mouseover listener on .fc-minor its working good but I cant able to get name attribute of my tr that is required time frame.

![timeclock1](https://user-images.githubusercontent.com/11496717/44068194-06b14b10-9fb8-11e8-83ff-0ff78777108f.png)

         let element1 = $(document).on('.fc-minor.KRISHN');
           element1.on(' mouseover', function(event: ElementRef) {
                 let va = element1.attr('class');
                 let eeee = element1.attr('name');
                 console.log('eeee is: ' + eeee );
                 console.log('va is: ' + va );
               }); 

console logs shows class and name or undefined 

![mouseover](https://user-images.githubusercontent.com/11496717/44068258-4b716c1c-9fb8-11e8-9a45-b0f0956fb4bd.png)

Can any one tell me what went wrong here.

Thank You

Regards

Gopikrishn

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
