### ISSUE TITLE
Maintain scroll position on events model change

### ISSUE THREAD

**Issue by shyamal890** [ng-fullcalendar/ng-fullcalendar#118]
Scroll position is reset to default one after a new event is added to events list:

https://stackblitz.com/edit/ng-fullcalendar-demo-zsgsl3?file=app%2Fapp.component.html

Just click on a day to add an event and you would see the scroll move back to default position.

**Comment by Jamaks** [comment]
it's issue in jquery fullcalendar too?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
