### ISSUE TITLE
Support for eventLongPressDelay

### ISSUE THREAD

**Issue by Shtibel** [ng-fullcalendar/ng-fullcalendar#119]
Hi there,
In the Fullfalendar.io docs there is an event: eventLongPressDelay
See the doc here: https://fullcalendar.io/docs/eventLongPressDelay

longPressDelay
eventLongPressDelay
selectLongPressDelay

It is thery helpfull for mobile dev.
Can you add a support for it?

Thank you.

**Comment by Jamaks** [comment]
Hi, in the next release

**Comment by Shtibel** [comment]
Hi @Jamaks 
Thank you for that!

Is there any due date for the next release ?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins

**Comment by Shtibel** [comment]
Hi @irustm ,
I am using the fullcalendar with ng-fullcalendar@2.0.0 on my IONIC application project.
The question is:
Is there a way to use long press gesture on an event.
So lets say if I long press on an event I can handle the event and show a popover / alert / modal

thank you

**Comment by irustm** [comment]
Hi, only https://fullcalendar.io/docs/touch
may be 
```
this.calendar.on('TRIGGER', (el) => )
```

**Comment by Shtibel** [comment]
Hi @irustm ,
This is not supported on the ng-fullcalendar@2.0.0

**Comment by irustm** [comment]
view:
https://github.com/ng-fullcalendar/ng-fullcalendar/blob/master/src/app/app.component.ts#L15
```
this.fullcalendar.calendar.on( ...
```

**Comment by sugeng-pdv** [comment]
> Hi there,
> In the Fullfalendar.io docs there is an event: eventLongPressDelay
> See the doc here: https://fullcalendar.io/docs/eventLongPressDelay
> 
> longPressDelay
> eventLongPressDelay
> selectLongPressDelay
> 
> It is thery helpfull for mobile dev.
> Can you add a support for it?
> 
> Thank you.

I'm Use 👍 ----> **longPressDelay: false**,
I succes use it's
