### ISSUE TITLE
contentHeight view specific option

### ISSUE THREAD

**Issue by w-veltman** [ng-fullcalendar/ng-fullcalendar#123]
Hi,

I was wondering if the 'contentHeight' option is handled in view-specific options, because if I set it to 'auto', for only my agendaWeek and agendaDay view, the option isn't handled properly.

If I set to view specific options the trailing white space at the bottom of agendaWeek and agendaDay is still shown. Which isn't the case when I set the 'contentHeight' option globally.

I have added images to illustrate my problem.

My code:
`      views: {
        month: {
          columnFormat: 'dddd',
        },
        agendaWeek: {
          columnFormat: 'dd DD-MM',
          slotLabelFormat: 'HH:mm',
          contentHeight: 'auto',
        },
        agendaDay: {
          columnFormat: 'dddd DD-MM-YYYY',
          slotLabelFormat: 'HH:mm',
          contentHeight: 'auto',
        }
      },`

The agendaDay view trailing white space:
![dayview](https://user-images.githubusercontent.com/29980599/44583595-35927300-a7a6-11e8-9fd2-729903e95670.PNG)

The agendaWeek view trailing white space:
![weekview](https://user-images.githubusercontent.com/29980599/44583596-35927300-a7a6-11e8-84ac-9882d64f52d9.PNG)

**Comment by Jamaks** [comment]
still an issue?

**Comment by w-veltman** [comment]
Nope sorry for not closing the issue. Closed it now.

**Comment by RyanEwen** [comment]
I'm having this issue in v4

```
            plugins: ['moment', 'momentTimezone', 'interaction', 'dayGrid', 'timeGrid', 'resourceDayGrid', 'resourceTimeGrid'],
            views: {
                timeGridDay: {
                    contentHeight: 'auto'
                },
                timeGridWeek: {
                    contentHeight: 'auto'
                },
                resourceDayGridDay: {
                    contentHeight: 'auto'
                }
            },
            header: {
                left: 'today prev,next',
                center: 'title',
                right: 'resourceDayGridDay,timeGridDay,timeGridWeek,dayGridMonth'
            },
```

The setting doesn't seem to have any effect unless at the top-level.

Wish I could just have the day and week views auto size to fit the height, like the month view.
