### ISSUE TITLE
Google Calendar integration problem

### ISSUE THREAD

**Issue by diegoooo82** [ng-fullcalendar/ng-fullcalendar#125]
Hi, I'm trying to integrate google calendars in ng-fullcalendar but the compiler tells me this error:

ERROR in src / app / app.component.ts (23.9): error TS2322: Type '{editable: true; eventLimit: false; header: {left: string; center: string; right: string; }; go ... 'is not assignable to type' Options'.
   Object literal may only specify known properties, and 'googleCalendarApiKey' does not exist in type 'Options'.

can someone help me?

**Comment by Jamaks** [comment]
Hi, Next, you must have all the required js/css files. This includes the standard fullcalendar.js and fullcalendar.css, in addition to gcal.js:

`
On Nov 17th 2014, Google shut down V1 and V2 of their Calendar APIs, which FullCalendar relied upon. Please upgrade to the latest version of FullCalendar or at least replace gcal.js with this file (will work down to FullCalendar v2.0.0). Also, your own Google Calendar API key is now required.
`
https://fullcalendar.io/docs/google-calendar

**Comment by diegoooo82** [comment]
I tried but it does not work
I added this code
```
            "scripts": [
              "node_modules/fullcalendar/dist/gcal.js"
            ]
```
in angular.json

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
