### ISSUE TITLE
dropping external events on fullcalendar is not working

### ISSUE THREAD

**Issue by reddyshashi85** [ng-fullcalendar/ng-fullcalendar#126]
Hi, 
I'm using ng-fullcalendar. When i'm trying to drop the external events on fullcalendar, its not dropping on fullcalendar and coming back to the position. Here I used ngDraggable to drag the external events. So please let me know if there is any way to solve this problem.

Thanks.

**Comment by Jamaks** [comment]
Hi! please publish a minimal project with this issue, which I could look at, thank you

**Comment by reddyshashi85** [comment]
Hi,
Please find the code in the link. 

Thanks.
[https://stackblitz.com/edit/ng-fullcalendar-drag-drop](url)

**Comment by Jamaks** [comment]
please try use https://codepen.io/pen/?&editors=001
with jquery-ui
but perhaps this will be added default in the second version ng-fulcalendar

**Comment by reddyshashi85** [comment]
Yes, I tried using jquery-ui, still its not working anymore.

[https://stackblitz.com/edit/ng-fullcalendar-drag-drop](url)

**Comment by reddyshashi85** [comment]
There is no droppable option in CalendarComponent options, may be because of that its not working.

**Comment by Jamaks** [comment]
still an issue?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
