### ISSUE TITLE
Not compatible with angular universal

### ISSUE THREAD

**Issue by Appjak34** [ng-fullcalendar/ng-fullcalendar#129]
When build angular universal and start the serve, broke

`$.fn.fullCalendar = function(options) {`
`TypeError: Cannot set property 'fullCalendar' of undefined`

**Comment by yomiex** [comment]
Hi, any updates on this?

**Comment by Tatenda** [comment]
If possible can someone help with this issue

**Comment by Jamaks** [comment]
Jquery Fullaclendar not supported in Universal mode, only browser.

**Comment by gitalvininfo** [comment]
Does Angular Fullcalendar support Universal? having the issue of ReferenceError: Element is not defined after upgrading to Angular Universal

**Comment by jgu7man** [comment]
I have the same problem here, Anybody finds solution or alternative?
