### ISSUE TITLE
2 way Data Binding not working when using ng-fullcalendar twice in an application

### ISSUE THREAD

**Issue by Gopikrishn** [ng-fullcalendar/ng-fullcalendar#130]
Hi There,

In my current application, I can select 2 calendars ( two different components ).

When I fire (select) event in one calendar it's firing in another calendar two . 

``<ng-fullcalendar #ucCalendar [id]="getCalendarID()" [ngClass]="getCalendarClass()" (select)="onSelectFunction($event, $event.detail)" [options]="calendarOptions" (eventClick)="eventClick($event.detail, $event)" (dayClick)="dayClick($event.detail)" (contextmenu)="onContextMenu($event, $event.detail)"
        (clickButton)="clickButtonEvent($event.detail)" (dayRender)="dayRenderFunction($event.detail, $event)" (eventRender)="eventRenderFunction($event.detail, $event)" (clickButton)="clickButton($event.detail)" (eventAfterRender)="oneventAfterRender($event.detail, $event)"
        (eventResize)="eventResize($event.detail)" (eventDrop)="onEventDropOrResize($event)" (eventDragStart)="oneventDragStart($event.detail)" (eventDragStop)="oneventDragStop($event.detail)" (drop)="onEventDrop($event.detail)" (eventMouseover)="onEventMouseOver($event)"
        (eventMouseout)="onEventMouseout($event)" (viewRender)="onViewRender($event)">
    </ng-fullcalendar>``

Can any one tell me why it happens?

Thanks

**Comment by Jamaks** [comment]
still an issue?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
