### ISSUE TITLE
clickButton event not working

### ISSUE THREAD

**Issue by PAWAN1SINGH** [ng-fullcalendar/ng-fullcalendar#131]
`  this.ucCalendar.fullCalendar('renderEvents', eventdata);
    this.ucCalendar.fullCalendar('option',{ eventRender: function(event:any, element:any, view:any) {
      element.find('span.fc-title').html(element.find('span.fc-title').text());
    }});
    this.ucCalendar.fullCalendar('rerenderEvents');`

this html is code
`  <ng-fullcalendar #ucCalendar [options]="calendarOptions" (eventClick)="eventClick($event.detail)" (eventDrop)="updateEvent($event.detail)"
        (eventResize)="updateEvent($event.detail)" (clickButton)="clickButton($event.detail)"></ng-fullcalendar>`

"clickButton" event not working with eventRender option if i remove eventRander function then "clickButton" working fine

**Comment by numsu** [comment]
I'm facing the same issue. It's not about the eventRender, it's about the fullCalendar('option', ...). If that function is called, the binding to clickButton disappears.

**Comment by numsu** [comment]
A workaround is calling `this.ucCalendar.ngAfterViewInit();` after `this.ucCalendar.fullCalendar('option', ...)`

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
