### ISSUE TITLE
selectConstraint should accept a string

### ISSUE THREAD

**Issue by lucas-md** [ng-fullcalendar/ng-fullcalendar#136]
As written in the [docs](https://fullcalendar.io/docs/selectConstraint), even in the [next version](https://fullcalendar.io/docs/v4/selectConstraint), the property selectConstraint in the options should accept a string 'businessHours'.

Currently, this prevents the correct use of the constraints in case of different business hours each day because an array of BusinessHours doesn't work either, only an object BusinessHours works but we can't specify different hours for each day.

You can find the issue in the index.d.ts file, interface SelectionOptions.

Thanks

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
