### ISSUE TITLE
How to apply multiple colors for events based on type of events.

### ISSUE THREAD

**Issue by sarath3940** [ng-fullcalendar/ng-fullcalendar#137]
Hi,
      I have a scenario where I get a list of events with a type(Like finished, unfinished). I want to apply green color for finished and red for unfinished. I have tried to apply "eventBackgroundColor", but it is applying for all the events. So, how could I achieve a solution for my issue? Help is appreciated. 

Thank you.

**Comment by Jamaks** [comment]
Hi, use event color, https://fullcalendar.io/docs/eventColor 
```
{
 ...
  color: black;
}
```

**Comment by sarath3940** [comment]
Sorry for the late reply. Thank you. But I want to apply different colors for different events at the same time. 
![doubt](https://user-images.githubusercontent.com/37688535/49086809-6d182c00-f27b-11e8-8853-625e8422d388.png)

**Comment by Jamaks** [comment]
exapmple
https://stackblitz.com/edit/ng-fullcalendar-demo-c2zppj?file=app/event.service.ts

**Comment by sarath3940** [comment]
Thank you.
