### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by thari119** [ng-fullcalendar/ng-fullcalendar#138]
Is there anyway to show the horizontal scroll bar on the resource scheduler day view?

**Comment by Jamaks** [comment]
Custom css: 
https://stackoverflow.com/questions/39130613/adding-horizontal-scroll-to-fullcalendar-scheduler

**Comment by apoklyak** [comment]
Any updates?

**Comment by irustm** [comment]
@apoklyak Please, try asking it in fullcalendar/core
