### ISSUE TITLE
Week Labels

### ISSUE THREAD

**Issue by akashkoul** [ng-fullcalendar/ng-fullcalendar#139]
Hi is there any way I can display full day name like 
Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday instead of
Sun, Mon, Tue, Wed, Thu, Fri, Sat

**Comment by maxwellt** [comment]
I think you'll find the `columnHeaderFormat` allows you to decide the format. You can read about it in the [documentation](https://fullcalendar.io/docs/columnHeaderFormat)

**Comment by Jamaks** [comment]
See please official documentation of fullcalendar
