### ISSUE TITLE
how to refresh view when get new data from backend service, thx

### ISSUE THREAD

**Issue by yogazx** [ng-fullcalendar/ng-fullcalendar#141]

**Comment by yogazx** [comment]
i used    $('#ucCalendar').fullCalendar('rerenderEvents');  but it didn't work

**Comment by Jamaks** [comment]
From 1.5.0 version new feature [(eventsModel)]="events" two events binding

<div *ngIf="calendarOptions">
    <ng-fullcalendar #ucCalendar [options]="calendarOptions" [(eventsModel)]="events"></ng-fullcalendar>
</div>
