### ISSUE TITLE
Events not rendering in safari browser

### ISSUE THREAD

**Issue by sohail0992** [ng-fullcalendar/ng-fullcalendar#143]
After assigning the values to events variable in proper format it's rendered perfectly on all other browsers except safari browser.
![screen shot 2019-01-03 at 6 16 35 pm](https://user-images.githubusercontent.com/23142014/50639668-1988b480-0f84-11e9-82db-35efa75f6e88.png)
![screen shot 2019-01-03 at 6 16 56 pm](https://user-images.githubusercontent.com/23142014/50639671-1988b480-0f84-11e9-8a8a-2ae9507c6d7d.png)

 attachment
Thanks

**Comment by hussainwajahat** [comment]
i have same problem but found no solution yet

**Comment by hussainwajahat** [comment]
Found a solution plz check the Date Format. Format of date should be 1/7/2019 event start or end Date.hopefully your problem is resolved.

**Comment by sohail0992** [comment]
(Safari 6.0(7536.25) on Mac) -- new Date('01-01-2000') is invalid whereas in other browsers it is perfectly valid. In these cases, you should replace all hyphens with forward-slashes so the result is something like new Date('01/01/2000'). 
Reference: 
https://stackoverflow.com/questions/9110644/fullcalendar-events-not-showing-up-only-on-safari
