### ISSUE TITLE
Angular 7.0 Compatibility

### ISSUE THREAD

**Issue by andlewis** [ng-fullcalendar/ng-fullcalendar#145]
Installing in an Angular 7.0+ project gives the following warnings:

npm WARN ng-fullcalendar@1.7.1 requires a peer of @angular/core@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-fullcalendar@1.7.1 requires a peer of @angular/common@>=4.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Fernandofat** [comment]
It gives the same warnings here.

**Comment by maxwellt** [comment]
It is for me @Fernandofat

**Comment by Jamaks** [comment]
done
