### ISSUE TITLE
calendar doesnt work in Internet Explorer 11

### ISSUE THREAD

**Issue by serojivanyan** [ng-fullcalendar/ng-fullcalendar#146]
I have a project with fullCalendar and it doesn't rendering in Internet Explorer 11. I started e new empty project and used ng-fullcalendar and again it hasn't worked, here is some screens.
![capture](https://user-images.githubusercontent.com/28952059/50728440-4931eb00-1143-11e9-87c1-ef24d4801fdb.PNG)
![captur1e](https://user-images.githubusercontent.com/28952059/50728443-4fc06280-1143-11e9-9f91-7fd64553f67f.PNG)
![capture1](https://user-images.githubusercontent.com/28952059/50728444-54851680-1143-11e9-846a-430f06be5108.PNG)

![capture2](https://user-images.githubusercontent.com/28952059/50728447-58b13400-1143-11e9-986a-1e0ce2cb3c41.PNG)

**Comment by Jamaks** [comment]
Uncomment src/polyfills.ts 
```
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
```
