### ISSUE TITLE
ng-fullcalendar has no exported member 'CalendarComponent

### ISSUE THREAD

**Issue by gattomannaro** [ng-fullcalendar/ng-fullcalendar#152]
Importing `import { CalendarComponent } from 'ng-fullcalendar';` i have an error. The error says that ng-fullcalendar has not exported member CalendarComponent. I can see that in the demo you have the same error. I tried with the versions 2.0.2 and 2.0.1.

**Comment by irustm** [comment]
Thanks!,
use please 2.0.3
