### ISSUE TITLE
Can not find module '@fullcalendar/core' 

### ISSUE THREAD

**Issue by Assdi** [ng-fullcalendar/ng-fullcalendar#153]
I have installed this module in angular 5 application.
and getting this error 

**Screenshots**
![image](https://user-images.githubusercontent.com/16256206/54606099-aa900780-4a6c-11e9-8cff-85c9c15e12de.png)

![image](https://user-images.githubusercontent.com/16256206/54608797-5b010a00-4a73-11e9-82a6-bbf6e01c1c35.png)

**Additional context**
my angular version is 5. and module is "ng-fullcalendar": "^2.0.3"

**Comment by irustm** [comment]
please install 
npm i --save @fullcalendar/core

and see demo https://github.com/ng-fullcalendar/ng-fullcalendar2-demo

**Comment by Assdi** [comment]
I have added this 

> "@fullcalendar/core": "^4.0.1",
    "@fullcalendar/daygrid": "^4.0.1",
    "@fullcalendar/interaction": "^4.0.1",
but this getting this error in component file

![image](https://user-images.githubusercontent.com/16256206/54611315-8508fb00-4a78-11e9-8690-2fe99d56330b.png)

**Comment by irustm** [comment]
did you watch the demo?

**Comment by Assdi** [comment]
Yes @irustm demo is working :-( . but not working on my side also getting error in terminal. 
![image](https://user-images.githubusercontent.com/16256206/54612500-e16d1a00-4a7a-11e9-8274-05b4bb7faf6d.png)

**Comment by Assdi** [comment]
this solved my problem . 
[https://github.com/fullcalendar/fullcalendar/issues/3991](url)

Thanks for your time @irustm

**Comment by Assdi** [comment]
this solved my problem . 
[https://github.com/fullcalendar/fullcalendar/issues/3991](url)

Thanks for your time @irustm

**Comment by CrisGarcis** [comment]
link not found

**Comment by NateJBeck** [comment]
For those of you using Angular 9 or 10 and following the [FullCalendar Angular plugin docs](https://fullcalendar.io/docs/angular), it's useful to know that running the install instruction results in an incomplete `package.json` -- not all required dependencies are installed (at least on Angular 10).

Per the [FullCalendar example Angular app](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular) I added the following packages to `package.json`

```
"@fullcalendar/angular": "^5.0.0",
"@fullcalendar/core": "^5.0.0",
"@fullcalendar/daygrid": "^5.0.0",
"@fullcalendar/interaction": "^5.0.0",
"@fullcalendar/timegrid": "^5.0.0",
"@fullcalendar/list": "^5.0.0",
```

After an `npm install` the calendar is showing up as expected, green compile. I have tested with basic functionality like binding `dateClick()` and an events[] -- looks good.

**Comment by shamsi2u** [comment]
> For those of you using Angular 9 or 10 and following the [FullCalendar Angular plugin docs](https://fullcalendar.io/docs/angular), it's useful to know that running the install instruction results in an incomplete `package.json` -- not all required dependencies are installed (at least on Angular 10).
> 
> Per the [FullCalendar example Angular app](https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/angular) I added the following packages to `package.json`
> 
> ```
> "@fullcalendar/angular": "^5.0.0",
> "@fullcalendar/core": "^5.0.0",
> "@fullcalendar/daygrid": "^5.0.0",
> "@fullcalendar/interaction": "^5.0.0",
> "@fullcalendar/timegrid": "^5.0.0",
> "@fullcalendar/list": "^5.0.0",
> ```
> 
> After an `npm install` the calendar is showing up as expected, green compile. I have tested with basic functionality like binding `dateClick()` and an events[] -- looks good.

This solved my issue for angular 10

**Comment by GRVLigiardi** [comment]
Try this : 
npm uninstall fullcalendar @fullcalendar/core @fullcalendar/interaction
And use DayPilot.
