### ISSUE TITLE
fullcalendar 4.0.0.1

### ISSUE THREAD

**Issue by saloumfall** [ng-fullcalendar/ng-fullcalendar#154]
Hello I have this error when I try to update fullcalendar. do you have any solution please?

TypeError: context.cmdFormatter is not a function

**Comment by irustm** [comment]
What version of fullcalendar do you use? 
`@fulcalendar/core` ?
`@angular/core` ?
see demo: https://github.com/ng-fullcalendar/ng-fullcalendar2-demo

**Comment by saloumfall** [comment]
thanks ! i use angular  core@7.2.0 and  fullcalendar@3.10.0

**Comment by irustm** [comment]
Use ng-fullcalendar@2.0.3 and @fullcalendar/core 4.0.1

**Comment by saloumfall** [comment]
I have the bug with these version ng-fullcalendar@2.0.3 and @fullcalendar/core 4.0.1! can be a conflict with momentjs ?

**Comment by irustm** [comment]
show me your issue in stackblitz
