### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by saloumfall** [ng-fullcalendar/ng-fullcalendar#155]
how can i add tooltip to event hover! thx

**Comment by irustm** [comment]
Use tooltip, and event render function, example: https://codepen.io/pen/?&editable=true&editors=001

**Comment by saloumfall** [comment]
Sorry !  the link is empty

**Comment by irustm** [comment]
https://codepen.io/anon/pen/bZmpbo?&editable=true&editors=001

**Comment by alexsintoni** [comment]
Hi,

I have an Angular project with the following dependencies installed:
```
    "@fullcalendar/angular": "^4.2.0",
    "@fullcalendar/core": "^4.2.0",
    "@fullcalendar/daygrid": "^4.2.0",
    "@fullcalendar/interaction": "^4.2.0",
    "@fullcalendar/list": "^4.2.0",
    "@fullcalendar/timegrid": "^4.2.0",
    "popper.js": "^1.15.0",
    "tooltip.js": "^1.3.2",
```
I tried the following solution as suggested in the template:
```
                <full-calendar #calendar
                    [editable]="true"
                    [defaultView]="'timeGridWeek'"
                    [header]="{
                                left: 'prev,next today',
                                center: 'title',
                                right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                            }"
                    [plugins]="calendarPlugins"
                    [weekends]="calendarWeekends"
                    [events]="calendarEvents"
                    [height]="'auto'"
                    [dir]="'ltr'"
                    [events]="calendarEvents"
                    (dateClick)="onDateClick($event)"
                    (eventClick)="onEventClick($event)"
                    (eventRender)="onEventRender($event)">
                </full-calendar>
```
and in the controller:
```
  onEventRender(info: any) {
    console.log('onEventRender', info.el);
    const tooltip = new Tooltip(info.el, {
      title: info.event.title,
      placement: 'top',
      trigger: 'hover',
      container: 'body'
    });
  }
```
I can see the calendar and the events but not tooltips.

What do I miss?

**Comment by irustm** [comment]
Hi! 
please reproduce your issue in stackblitz.com
https://stackblitz.com/edit/fullcalendar-angular-demo

**Comment by alexsintoni** [comment]
Hi @irustm 

I apologize for the delay.
I tried on [stackblitz](https://stackblitz.com/edit/fullcalendar-angular-demo-jrczw7?file=src%2Fapp%2Fapp.component.ts) as you suggested and it works.
I guess I have a small difference in my project that I am not able to figure it out.

I will try to find out the differences. Thanks a million for the help.

One last question, do you know if it  is possible to customize the tooltip with something nicer?
Something like an Angular component?

**Comment by ismadox** [comment]
You only provided a js solution which cant work with angular, that is just silly!
pls provide an angular solution or access to single events with ng-template!!!!
@irustm
