### ISSUE TITLE
Change overall events in ng-fullcalendar & coding confirmation

### ISSUE THREAD

**Issue by Jai-Kumaresh** [ng-fullcalendar/ng-fullcalendar#157]
I use fullcalendar for doctor schedule.
![IRIS](https://user-images.githubusercontent.com/43090102/54803388-561ba080-4c95-11e9-951b-08dd393b8dce.png)
![IRIS1](https://user-images.githubusercontent.com/43090102/54803404-659ae980-4c95-11e9-93e4-05f067a84f00.png)

![Screenshot from 2019 03 22 11 27 22](https://user-images.githubusercontent.com/43090102/54803452-92e79780-4c95-11e9-9765-9f2ebc393f30.png)

It's correct flow or not. please tell me

**Comment by irustm** [comment]
Try use `[(eventsModel)]="events"`

and update events array
```
 this.events = []; // new array
```

**Comment by Jai-Kumaresh** [comment]
@irustm  It's already tried. But i have error. 
`Can't bind to 'eventsModel' since it isn't a known property of 'ng-fullcalendar'.`
If you know that solution. Please tell me.

**Comment by irustm** [comment]
what version of ng-fullcalendar?
see demo:
https://stackblitz.com/edit/ng-fullcalendar2-demo

**Comment by Jai-Kumaresh** [comment]
@irustm  Thank you it's work for my need.

**Comment by Jai-Kumaresh** [comment]
#4572
@irustm  If you know that solution. Please tell me.

**Comment by Jai-Kumaresh** [comment]
[#4572](https://github.com/fullcalendar/fullcalendar/issues/4572)
@irustm If you know that solution. Please tell me.
