### ISSUE TITLE
timeGridWeek, timeGridDay not showing up

### ISSUE THREAD

**Issue by tschmidtbhv** [ng-fullcalendar/ng-fullcalendar#159]
Hello I facing a problem, currently the timeGridWeek and timeGridDay views are not rendered. I also checked your example at stackblitz and saw there is the same problem.

**Comment by irustm** [comment]
Hi! use plugin https://fullcalendar.io/docs/timegrid-view

example:
```
import { Calendar } from '@fullcalendar/core';
import timeGridPlugin from '@fullcalendar/timegrid';
...

  plugins: [ timeGridPlugin ],
  defaultView: 'timeGridWeek'
...
```

**Comment by es404020** [comment]
ajanieniola@Ajanis-MacBook-Pro  ~/Documents/privitest   users-presense ●  npm install --save @fullcalendar/angular @fullcalendar/daygrid  @fullcalendar/timegrid

**Comment by aliahmad900** [comment]
important to include daygrid and timegrid  together to work timegrid normali .
and import daygrid before timegrid
