### ISSUE TITLE
Styling [css] problem

### ISSUE THREAD

**Issue by pzabrocki** [ng-fullcalendar/ng-fullcalendar#162]
I followed instructions and saw this
https://www.awesomescreenshot.com/image/3939969/eccb36221b800188b816e7ec25e440e1
No css.
So i added `@import '../node_modules/@fullcalendar/core/main.min.css';`  to my global.css file and it's much better, but I can't see calendar cells on page load:
https://www.awesomescreenshot.com/image/3939972/48f5678ef4822c2924140a986bdfea5b

They render only if I resize window or click something:
https://www.awesomescreenshot.com/image/3939974/d21c3a7348352b98b607b7afcf916e8b

There are also other css problems, but these are most important. Do you know something about it? How do you load fullcalendar css?

   Ionic Framework               : @ionic/angular 4.1.2
   @angular/cli                  : 7.2.4

Thanks

**Comment by pzabrocki** [comment]
Ok, it was a problem with my node modules. I deleted everything and installed from scratch using NVM.

**Comment by ShahoG** [comment]
Having the same issue, deleted node modules but still getting the exact same problem, please advice
