### ISSUE TITLE
External Draggable feature

### ISSUE THREAD

**Issue by thismarcoantonio** [ng-fullcalendar/ng-fullcalendar#20]
Would be nice to have a external draggable like the Fullcalendar without jQuery UI.
Demo: https://fullcalendar.io/js/fullcalendar-3.8.0/demos/external-dragging.html

**Comment by TyreX6** [comment]
would you please give us an example of dragging events If this feature was added in the new release ?

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
