### ISSUE TITLE
How can I add CustomButtons

### ISSUE THREAD

**Issue by emartinrda** [ng-fullcalendar/ng-fullcalendar#65]
The Options let me to add custombuttons, but is not possible to correctly configure the 'click' property.

How can I manage this?

Thank you in advance!

Elias.

**Comment by Jamaks** [comment]
Its new features, I will implement it in the next release.

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
and see demo

**Comment by TejasCMehta** [comment]
How I can implement custom button as datepicker like example here ?
https://github.com/fullcalendar/fullcalendar/issues/496#issuecomment-132532410
