### ISSUE TITLE
How to create removeEvents?

### ISSUE THREAD

**Issue by mikenlanggio** [ng-fullcalendar/ng-fullcalendar#68]
Hi,
I am tried add removeEvent use EventRender or EventClick, but both is not working.
`    this.calendarOptions = {
      editable: true,
      eventLimit: false,
      header: {
        left: 'prev',
        center: 'title',
        right: 'next'
      },
      events: [
        {
          title: ' New event New event New event New event New event New event New event New event ',
          start: '2018-03-26',
          end: '2018-03-29',
        }
      ],
      eventAfterAllRender: function(view) { <--- working
        console.log('after render');  
      },
      eventRender: function (event, element) { <-- not working
        alert('eventRender');
        element.find('.content-right').click(function () {
          $('div#calendar').fullCalendar('removeEvents', event._id);
        });
      },
      eventClick: function(view){  <-- not working
        alert('eventClick');
      },
    };
`

Thank you

**Comment by Jamaks** [comment]
removeEvent use EventRender or EventClick is output functions use example
` <ng-fullcalendar (removeEvent) = removeEvent($event.detail)">`

**Comment by mikenlanggio** [comment]
It not in output function.
HTML:
(removeEvent) = removeEvent()"
TS:
removeEvent(){
console.log('working');
}

I not found any console log

**Comment by Jamaks** [comment]
Sorry remove event is non callback function

outputs: 

```
  clickButton
  eventClick
  eventDrop
  eventResize
  eventRender
  windowResize
  viewRender
  viewDestroy
  initialized
  select
  unselect
  dayClick
  navLinkDayClick
  navLinkWeekClick
```

**Comment by mikenlanggio** [comment]
I want to add function delete event.
I custom icon Delete each event like this
https://uphinhnhanh.com/images/2018/03/26/image66c9b.png
But i don't know how to create Trigger delete this :(.
You have any solution?
Thank you

**Comment by mikenlanggio** [comment]
I tried eventClick by ClassName.
But ClassName always null.
https://uphinhnhanh.com/images/2018/03/26/image0c0dc.png
I dont have any idea to create removeEvent

**Comment by Jamaks** [comment]
try <ng-fullcalendar (click)="click($event)">

**Comment by mikenlanggio** [comment]
Thank you so much!! :)
Can i donate for you? :)

**Comment by Jamaks** [comment]
No thanks :), click star button please)
 http://joxi.ru/VrwdYwlCK6JK3m

**Comment by mikenlanggio** [comment]
Of cource. :).
Ah, I have new trouble.
If i use (click), i can't get infomation of event like id event. Any new idea? Thank you

**Comment by Jamaks** [comment]
I need to add a new property for the output(may be), create please a small project with issue

**Comment by mikenlanggio** [comment]
Okay. 
I just have found a solution :).
But hope new version from you. 
Thank you :)

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
