### ISSUE TITLE
ng-calendar crashes when changing view. 

### ISSUE THREAD

**Issue by bogandy99** [ng-fullcalendar/ng-fullcalendar#73]
After the calendar loads the month view, if I change it do day or week view it freezes and chrome kills the tab.

If I set the calendar to start with the day view ( defaultView: 'agendaDay' ) it doesn't even show the calendar anymore.

package-json snippet:
 "fullcalendar": "3.6.1",
    "fullcalendar-scheduler": "1.9.1",
    "ng-fullcalendar": "1.5.5",

Another issue I noticed is if I upgrade to fullcalendar 3.8.1, compilation fails with 

ERROR in node_modules/fullcalendar/dist/fullcalendar.d.ts(2525,10): error TS2403: Subsequent variable declarations must have the same type.  Variable 'fullCalendar' must be of type 'Calendar', but here has type 'object'.
node_modules/ng-fullcalendar/src/calendar.component.d.ts(3,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.
src/app/modules/+appointment/overview/appointment.component.ts(29,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.

But this should probably be another issue.

**Comment by Jamaks** [comment]
Hi!
Please add example project with bug, in stackblitz, plunker, github.

fullcalendar after 3.6.1 not supported yet

**Comment by bogandy99** [comment]
Hi, 
It's rather easy to reproduce it. 
Get the ng-fullcalendar-demo project and in the app.component.ts set the slotDuration to 20

ngOnInit() {
    this.calendarOptions = {
      editable: true,
      eventLimit: false,
      slotDuration: 20,
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'day,month,agendaWeek,agendaDay,listMonth'
      },
      events: []
    };
  }

Afterwards compile and run and click on the 'Day' view.

**Comment by LorenzoGramola** [comment]
That's not an issue: if you read the stack error you will see

> Module ''fullcalendar'' has no exported member 'Options'.
> src/app/modules/+appointment/overview/appointment.component.ts(29,10): error TS2305: Module ''fullcalendar'' has no exported member 'Options'.


By the way you should have a compiler error at compile time, anyhow.. 
Looking at the code you posted there is a simple error in the slotDuration. If you read the comment about slotDuration in Options (the one mentioned in the error.....) it says:
/**
     * The frequency for displaying time slots.
     *
     * default: '00:30:00'
     */
and it's referrenced type is moment.Duration so either you just set it to '00:20:00' and you won't have problem but a compilation Error (types are not matching) or you give it the right typed duration expected (see below)

You need _moment_ and then in your code you just do the following ( i just modified the code you provided)

 let duration = moment.duration(15, 'minutes');  
    this.calendarOptions = {
      editable: true,
      eventLimit: false,
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'day,month,agendaWeek,agendaDay,listMonth'
      },
      slotDuration: duration,
      events: []
    };

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
