### ISSUE TITLE
Support for latest version of FullCalendar

### ISSUE THREAD

**Issue by vz28bh** [ng-fullcalendar/ng-fullcalendar#83]
FullCalendar is currently at 3.9.0 but this component is at 3.6.1 Will that get updated anytime soon? 

Kind of related is the general question of maintenance. Are you going to be maintaining this or was it just a project to meet a goal and you will move on? Either way, thanks for your work so far!

**Comment by Jamaks** [comment]
Yes, I want to update the project to the latest version in the near future. As soon as there is a little time

**Comment by kpakur** [comment]
have a look
https://github.com/Jamaks/ng-fullcalendar/pull/90

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
