### ISSUE TITLE
eventClick does not include jsEvent and view in the details

### ISSUE THREAD

**Issue by vz28bh** [ng-fullcalendar/ng-fullcalendar#84]
https://github.com/Jamaks/ng-fullcalendar/blob/704ea605d85467235fdaa2dd00c63c969a560e5f/src/lib/src/calendar.component.ts#L135

FullCalendar provides this info

$('#calendar').fullCalendar({
  eventClick: function(calEvent, jsEvent, view) {
...

**Comment by AlekseiPinchuk** [comment]
The same problem. Any updates for this issue?

**Comment by ntsadu** [comment]
Still no solution or workaround found for this. The entire calendar is returned as the target element in the custom event event though I clicked on a specific event. There is no reasonable way to display a popover relative to the event's position in the calendar.. Anyone?

**Comment by ntsadu** [comment]
I also think it's not fair to tell users to refer to the original full-calendar docs when you callback signatures don't even match.. You could at least provide ng-fullcalendar subset docs

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
