### ISSUE TITLE
Multiple calendars on the same page

### ISSUE THREAD

**Issue by kombadzomba** [ng-fullcalendar/ng-fullcalendar#86]
I have two calendars on one page and my task is to show the Save All button above each one of them when calendar events are dragged inside. I've made component having Save All button with `*ngIf` condition and `<ng-fullcalendar>` with `(eventDrop)="onEventDropOrResize($event)"`. 

Dropping the calendar event in the second calendar triggers the `onEventDropOrResize()` method in the first component and the Save All button shows always in the first component. While debugging, `$event.srcElement` and `$event.target` are both pointing to the first `<ng-fullcalendar>` DOM element. I've tried with other events, i.e. `eventClick()` and the event always triggers the first component's listener method.

Is there a quick workaround for this?

**Comment by kombadzomba** [comment]
Update: This was the issue with ng-fullcalendar v1.5.5

In 1.5.6 event is fired to all calendars on the page ([link](https://github.com/Jamaks/ng-fullcalendar/blob/c3af7106960cd2cd06f0a4ea1f667e815077435e/src/lib/src/calendar.component.ts#L119)) so the problem is still there but less serious. I had to patch this in `eventDrop` method by checking if received calendar event exists in the current component.

**Comment by Jamaks** [comment]
Make 2 calendar options and different output functions. Ex
```
first calendar #ucCalendar1
(eventDrop)="onEventDropOrResize1($event)"

first calendar #ucClendar2
(eventDrop)="onEventDropOrResize1($event)"
```

**Comment by kombadzomba** [comment]
Hi @Jamaks,

Calendars with different ref names are not the option since I need to add them dynamically as user preference on their dashboard.

However, I've patched mine, so I am happy, and thanks for the nice work on the package! 👍

**Comment by tomifida** [comment]
Hi @kombadzoma,
If im correct you achieved to externally add events from one calendar to another? If so could you please show me how did you achieved to do that. 2 days ago Jamakas god bless him added also the drop event emitter for external events, but im not able to get it working( I cant drop events from one calendar to another)

**Comment by tomifida** [comment]
@kombadzomba thanks for your blitz answer.
I want to implement this example ([https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/external-dragging.html].) 2 Days ago Jamakas addedd event emitter for this called "drop", but im having trouble on making it work.
As per when i drop events from one to another calendar nothing happens. Maybe this functionality is not fully implemented yet( for the drop event ).

**Comment by kombadzomba** [comment]
From the fullcalendar dropEvent documentation:

"The eventDrop callback does not get called when an external event is dragged onto the calendar."

If I understood correctly, you need to properly initialize draggable elements and using events from other calendar is not an option. Jamaks can do nothing about it.

https://fullcalendar.io/docs/droppable

**Comment by kombadzomba** [comment]
Take a look:
https://github.com/angular-ui/ui-calendar/issues/43

**Comment by tomifida** [comment]
You are correct, i want to make draggable elements to be droppable in the calendar(calendar to calendar was a misconception of mine. The eventDrop callback i know its not called fro external events but 2 days ago he added the drop callback which is called when a valid external jQuery UI draggable has been dropped onto the calendar.
I know they were able to implement what im looking for in the link you sent, but that is written in angularJS, has no support for angular 2 4 5
Anyways thank you soo much for your time :)

**Comment by kombadzomba** [comment]
I guess you'll have to add jQueryUI into ng2 project or maybe try some other ng2 draggable package first.

**Comment by mitjarogl** [comment]
@Jamaks How can I initialise two instances of calendar on same page? I cannot find from documentation. Currently by default if I try to add two calendars they all have same id.

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
