### ISSUE TITLE
Events are still rendered even if eventRender returns false

### ISSUE THREAD

**Issue by IsaacDignadice** [ng-fullcalendar/ng-fullcalendar#95]
Hi Jamaks,

EventRender is not reacting as expected. I have initialized it as an @Output EventEmitter  
<ng-fullcalendar #ucCalendar (eventRender)="eventRender($event.detail)"[options]="calendarOptions"></ng-fullcalendar>

and returned false on the eventRender function but still the events are rendered. Hoping for your response. Thank you so much.

**Comment by joaodforce** [comment]
Same here, and also if you put the event callback on the options object, it wont work, the eventRender event only gets called if you put it on the directive.

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins

**Comment by Troymlandon** [comment]
I'm actually also having this problem with @fullcalendar/angular@4.2.1.

I have `<full-calendar #calendar *ngIf="options" defaultView="dayGridMonth" [plugins]="options.plugins" [events]="events"
  (eventClick)="eventClick($event)" (eventRender)="eventRender($event)" [header]="options.header"
  [titleFormat]="options.titleFormat"></full-calendar>`

and `eventRender(info) {
  return false
}`

but the events render anyways
